sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: groovy

env:
- TERM=dumb

install: true

before_script:
  - ./gradlew --version

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew test jacocoTestReport coveralls
  #- jdk_switcher use openjdk7
  #- ./gradlew test jacocoTestReport coveralls