= Pug (Jade) Spring Boot Starter

'''

This Starter provides you the minimal and required configuration to use https://pugjs.org[pug/jade templates] as views in your Spring Boot application.

Behind the scenes, this starter uses the https://github.com/neuland/pug4j[pug4j] and https://github.com/neuland/spring-pug4j[spring-pug4j] libraries.

== Environment

image:https://img.shields.io/badge/JDK-17+-green.svg["JDK"]
image:https://img.shields.io/badge/Spring%20Boot-3.4.1-green.svg["Spring Boot"]

== GitHub, Factoids and Stats

image:https://img.shields.io/github/forks/0x100/pug-spring-boot-starter.svg?style=flat["Forks", link="https://github.com/0x100/pug-spring-boot-starter/network"]
image:https://img.shields.io/github/release/0x100/pug-spring-boot-starter.svg?style=flat["Release", link="https://github.com/0x100/pug-spring-boot-starter/releases"]
image:https://img.shields.io/github/issues/0x100/pug-spring-boot-starter.svg?style=flat["Issues", link="https://github.com/0x100/pug-spring-boot-starter/issues"]

++++
<script type="text/javascript" src="https://openhub.net/p/pug-spring-boot-starter/widgets/project_basic_stats.js"></script>
++++

'''

== Usage

The usage is pretty straightforward as you can expect for any Spring Boot Starter


=== Add Maven dependency
`build.gradle`
[source,ruby]
----
...
dependencies {
  compile "ru.ilya.lysenko:pug-spring-boot-starter:3.0.1"
}
...
----


`pom.xml`
[source,xml]
----
<project>
  ...
  <dependencies>
    <dependency>
      <groupId>ru.ilya.lysenko</groupId>
      <artifactId>pug-spring-boot-starter</artifactId>
      <version>3.0.1</version>
    </dependency>
  </dependencies>
</project>
----

=== Pug templates
Add the pug templates in the following directory
[indent=0]
----
  src
  └── main
      └── resources
          └── templates
              └── index.pug
----

Then you can add new Spring MVC controllers as usual

---

== Helpers
You can add https://github.com/neuland/pug4j#helpers[helpers] automatically using the annotation https://github.com/domix/jade4j-spring-boot-starter/blob/master/src/main/java/com/domingosuarez/boot/autoconfigure/pug4j/PugHelper.java[@PugHelper]

[source,java]
----
package demo;

import com.domingosuarez.boot.autoconfigure.pug4j.JadeHelper;

@PugHelper
public class Util {
  public String format(double number) {
    return "some formating";
  }
}
----

`template.pug`
----
html
  head
    title Hello
  body
    h
    h1
      #{util.format(4)} # <1>
----
<1> The helper name's is the Spring Bean id


=== Customize the helper's name
You can customize the helper's name using the https://github.com/domix/jade4j-spring-boot-starter/blob/master/src/main/java/com/domingosuarez/boot/autoconfigure/pug4j/PugHelper.java[PugHelper] annotation
[source,java]
----
package demo;

import pug4j.autoconfigure.ru.ilya.lysenko.PugHelper;

@PugHelper("myId") // <1>
public class Util {
  public String format(double number) {
    return "some formating";
  }
}
----
<1> The new id

`template.pug`
----
html
  head
    title Hello
  body
    h
    h1
      #{myId.format(4)}
----

---

== Configuration

The following settings are available:

[format="csv", options="header"]
|===
Setting key, Type, Default value
spring.pug4j.checkTemplateLocation, Boolean, true
spring.pug4j.prefix, String, 'classpath:/templates/'
spring.pug4j.suffix, String, '.pug'
spring.pug4j.encoding, String, 'UTF-8'
spring.pug4j.caching, Boolean, true
spring.pug4j.prettyPrint, Boolean, false
spring.pug4j.mode, String, 'HTML'
spring.pug4j.contentType, String, 'text/html'
spring.pug4j.resolver.order, Integer, Ordered.LOWEST_PRECEDENCE - 50
|===

---

== Complete demo application

Please take a look into this https://github.com/domix/jade4j-spring-boot-starter-showcase[application] if you want to checkout a fully application.
